# Generated by Django 3.2.8 on 2021-10-30 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ceo', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('company_slogan', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('last_update_time', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('last_update_time', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(choices=[('Dodoma', 'Dodoma'), ('Arusha', 'Arusha'), ('Kilimanjaro', 'Kilimanjaro'), ('Tanga', 'Tanga'), ('Morogoro', 'Morogoro'), ('Pwani', 'Pwani'), ('Dar es Salaam', 'Dar es Salaam'), ('Lindi', 'Lindi'), ('Mtwara', 'Mtwara'), ('Ruvuma', 'Ruvuma'), ('Iringa', 'Iringa'), ('Mbeya', 'Mbeya'), ('Songwe', 'Songwe'), ('Singida', 'Singida'), ('Tabora', 'Tabora'), ('Rukwa', 'Rukwa'), ('Kigoma', 'Kigoma'), ('Shinyanga', 'Shinyanga'), ('Kagera', 'Kagera'), ('Mwanza', 'Mwanza'), ('Mara', 'Mara'), ('Manyara', 'Manyara'), ('Njombe', 'Njombe'), ('Katavi', 'Katavi'), ('Simiyu', 'Simiyu'), ('Geita', 'Geita'), ('Unguja Kaskazini', 'Unguja Kaskazini'), ('Unguja Kusini', 'Unguja Kusini'), ('Unguja Mjini Magharibi', 'Unguja Mjini Magharibi'), ('Pemba Kaskazini', 'Pemba Kaskazini'), ('Pemba Kusini', 'Pemba Kusini')], max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_employee.company')),
            ],
            options={
                'db_table': 'tb_office',
                'ordering': ['-id'],
                'unique_together': {('company', 'name', 'region', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos/employee')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('last_update_date', models.DateField(auto_now=True)),
                ('last_update_time', models.DateField(auto_now=True)),
                ('companies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_branches', to='pr_employee.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr_employee.department')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_office', to='pr_employee.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_employee',
            },
        ),
    ]
