# Generated by Django 3.2.8 on 2021-10-30 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='tb_companies',
        ),
    ]
