# Generated by Django 3.2.8 on 2021-10-30 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr_employee', '0002_alter_company_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='l_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='middle_name',
            new_name='m_name',
        ),
    ]
